# Generated by Django 4.2.13 on 2026-05-17 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('uom_type', models.CharField(choices=[('MIN', 'Numeric/Percentage (Higher is Better)'), ('MAX', 'Numeric (Lower is Better)'), ('TIMELINE', 'Timeline/Date-based'), ('ZERO', 'Zero-based (Zero = Success)')], max_length=10)),
                ('target', models.FloatField()),
                ('thrust_area', models.CharField(max_length=200)),
                ('cycle_year', models.IntegerField()),
                ('pushed_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_shared_goals', to=settings.AUTH_USER_MODEL)),
                ('primary_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_shared_goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoalSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_year', models.IntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('MANAGER_REVIEW', 'Manager Review'), ('APPROVED', 'Approved'), ('RETURNED', 'Returned for Rework')], default='DRAFT', max_length=20)),
                ('is_locked', models.BooleanField(default=False)),
                ('return_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_sheets', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_sheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cycle_year', 'employee__full_name'],
                'unique_together': {('employee', 'cycle_year')},
            },
        ),
        migrations.CreateModel(
            name='GoalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('thrust_area', models.CharField(max_length=200)),
                ('uom_type', models.CharField(choices=[('MIN', 'Numeric/% (Higher is Better)'), ('MAX', 'Numeric (Lower is Better)'), ('TIMELINE', 'Timeline/Date-based'), ('ZERO', 'Zero-based')], max_length=10)),
                ('target', models.FloatField()),
                ('weightage', models.IntegerField()),
                ('achievement', models.FloatField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('is_synced_achievement', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='goals.goalsheet')),
                ('shared_goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_entries', to='goals.sharedgoal')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
