# Generated by Django 4.2.13 on 2026-05-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuarterWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_year', models.IntegerField()),
                ('quarter', models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=2)),
                ('window_opens', models.DateField()),
                ('window_closes', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['cycle_year', 'quarter'],
                'unique_together': {('cycle_year', 'quarter')},
            },
        ),
    ]
