# Generated by Django 4.2.13 on 2026-05-17 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=2)),
                ('planned_target', models.FloatField()),
                ('actual_achievement', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('ON_TRACK', 'On Track'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=15)),
                ('employee_note', models.TextField(blank=True)),
                ('manager_comment', models.TextField(blank=True)),
                ('checked_in_at', models.DateTimeField(auto_now_add=True)),
                ('manager_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('goal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='goals.goalentry')),
            ],
            options={
                'ordering': ['quarter'],
                'unique_together': {('goal_entry', 'quarter')},
            },
        ),
    ]
