# Generated by Django 4.2.13 on 2026-05-17 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escalation_type', models.CharField(choices=[('NO_SUBMISSION', 'Goal Sheet Not Submitted'), ('NO_CHECKIN', 'Check-in Not Completed'), ('OVERDUE', 'Goal Overdue'), ('MANUAL', 'Manual Escalation')], max_length=20)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to=settings.AUTH_USER_MODEL)),
                ('notified_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_escalations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
    ]
